networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge

services:
  postgresql:
    container_name: postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD
        - pg_isready
        - -h
        - 127.0.0.1
        - -p
        - "5432"
        - -q
        - -U
        - root
      timeout: 5s
    image: postgres:18.1-alpine
    networks:
      - spring_cloud_default
    ports:
      - 5432:5432
    restart: always
